### ISSUE TITLE
Achieve Good-Standing with Ledger

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/ledger-app#29]
The community has created an EOSIO client for [Ledger](https://www.ledger.com) hardware wallets, but the app is falling out of good-standing with Ledger's requirements to continue to be available to users. This issue tracks ENF effort upgrading the app to ensure good-standing is maintained so the app continues to be distributed.

**Comment by ericpassmore** [comment]
Types of releases as defined by Ledger documented here. https://developers.ledger.com/docs/nano-app/publish-introduction/

Currently we are a Public release. Failing to meet the standard for public releases our app would be classified as an unaudited developer release.

**Comment by ericpassmore** [comment]
completed
